version: 2

jobs:
  build:
    working_directory: ~/Coiny
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run:
          name: Download Waldo CLI
          command: |
            curl -fLs https://github.com/waldoapp/waldo-cli/releases/download/1.1.0/waldo > .circleci/waldo
            chmod +x .circleci/waldo
      - run:
          name: Configure Android Licences
          command: |
            mkdir "${ANDROID_HOME}/licenses" || true
            echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"
            echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "${ANDROID_HOME}/licenses/android-sdk-license"
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew --stacktrace androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Android build
          command: ./gradlew --stacktrace assemble check
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Upload build to Waldo
          command: .circleci/waldo "$WALDO_BUILD_PATH"
          environment:
            WALDO_UPLOAD_TOKEN: 7a7e9756f753bc9feeab80a15b9ea201
            WALDO_BUILD_PATH: app/build/outputs/apk/debug/app-debug.apk
